# Generated by Django 3.2.9 on 2021-12-22 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_list', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('scopes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.object')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.article')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='articles',
            field=models.ManyToManyField(related_name='tags', through='articles.Relationship', to='articles.Article'),
        ),
    ]
