# Generated by Django 3.2.9 on 2021-12-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211222_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='articles',
            field=models.ManyToManyField(related_name='scope', through='articles.Relationship', to='articles.Object'),
        ),
    ]
