# Generated by Django 3.2.9 on 2021-12-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_tag_list_object_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Tegs',
        ),
    ]
