# Generated by Django 3.2.9 on 2022-01-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
